const path=require('path');const http=require('http');const crypto=require('crypto');const express=require('express');const{Server}=require('socket.io');const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:true,credentials:true}});const rooms=new Map();const PORT=process.env.PORT||3000;
app.use(express.static(path.join(__dirname,'public')));app.get('/health',(_req,res)=>res.json({ok:true,rooms:rooms.size}));app.get('*',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const choices=new Set(['rock','paper','scissors']);const cleanName=n=>String(n||'').trim().slice(0,20);const cleanTarget=v=>Math.min(10,Math.max(1,Number.parseInt(v,10)||3));const makeCode=()=>{let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c};
const publicRoom=(r,message='')=>({code:r.code,phase:r.phase,message,targetWins:r.targetWins,isPublic:r.isPublic,players:r.players.map(p=>p?{name:p.name,ready:p.ready,score:p.score}:null),spectatorCount:r.spectators.size});
const broadcastState=(r,m='')=>io.to(r.code).emit('state',publicRoom(r,m));
const lobbyRooms=()=>[...rooms.values()].filter(r=>r.isPublic&&r.players.some(Boolean)&&r.phase!=='finished').map(r=>({code:r.code,host:r.players.find(Boolean)?.name||'Spieler',players:r.players.filter(Boolean).length,targetWins:r.targetWins,phase:r.phase,spectatorCount:r.spectators.size}));
function broadcastLobbies(){io.emit('public-lobbies',lobbyRooms())}
function closeRoom(r){if(r.finishTimer)clearInterval(r.finishTimer);rooms.delete(r.code);io.to(r.code).emit('room-closed');r.spectators.forEach(id=>io.sockets.sockets.get(id)?.disconnect(true));broadcastLobbies()}
function finishMatch(r,winner,reason=''){if(!rooms.has(r.code)||r.phase==='finished')return;r.phase='finished';let n=10;io.to(r.code).emit('match-finished',{winner,seconds:n,reason});r.finishTimer=setInterval(()=>{n--;if(n>0)io.to(r.code).emit('match-countdown',{seconds:n});else closeRoom(r)},1000);broadcastState(r,reason||'Match beendet.');broadcastLobbies()}
function forfeit(r,leaverIndex){const remaining=r.players[leaverIndex===0?1:0];if(remaining)finishMatch(r,remaining.name,'Der andere Spieler hat die Runde verlassen.');else closeRoom(r)}
function finishRound(r){const[a,b]=r.players;if(!a||!b||!a.choice||!b.choice)return;const w=a.choice===b.choice?'draw':((a.choice==='rock'&&b.choice==='scissors')||(a.choice==='scissors'&&b.choice==='paper')||(a.choice==='paper'&&b.choice==='rock')?'playerOne':'playerTwo');if(w==='playerOne')a.score++;if(w==='playerTwo')b.score++;r.phase='result';io.to(r.code).emit('round-result',{choices:[a.choice,b.choice],winner:w,scores:[a.score,b.score],draw:w==='draw',targetWins:r.targetWins});if(a.score>=r.targetWins||b.score>=r.targetWins){finishMatch(r,a.score>=r.targetWins?a.name:b.name);return}setTimeout(()=>{if(!rooms.has(r.code)||r.phase==='finished')return;a.choice=b.choice=null;a.ready=b.ready=false;r.phase='playing';io.to(r.code).emit('round-reset');broadcastState(r);},2200)}
io.on('connection',s=>{
 s.on('list-public-rooms',ack=>{ack(lobbyRooms())});
 s.on('create-room',({name,targetWins,isPublic},ack)=>{name=cleanName(name);if(!name)return ack({error:'Bitte gib einen Namen ein.'});const r={code:makeCode(),targetWins:cleanTarget(targetWins),isPublic:Boolean(isPublic),players:[{id:s.id,name,choice:null,ready:false,score:0},null],spectators:new Set(),phase:'waiting',finishTimer:null};rooms.set(r.code,r);s.join(r.code);s.data.room=r.code;s.data.role=0;ack({ok:true,code:r.code,role:'player',targetWins:r.targetWins});broadcastState(r,`Warte auf den zweiten Spieler. Ziel: ${r.targetWins} Sieg${r.targetWins===1?'':'e'}.`);broadcastLobbies()});
 s.on('join-room',({code,name},ack)=>{name=cleanName(name);code=String(code||'').trim().toUpperCase();const r=rooms.get(code);if(!name)return ack({error:'Bitte gib einen Namen ein.'});if(!r)return ack({error:'Raum nicht gefunden.'});if(r.phase==='finished'||(r.players[0]&&r.players[1]))return ack({error:'Dieser Raum ist bereits voll.'});const slot=r.players[0]?1:0;r.players[slot]={id:s.id,name,choice:null,ready:false,score:0};s.join(code);s.data.room=code;s.data.role=slot;ack({ok:true,code,role:'player',targetWins:r.targetWins});r.phase='playing';broadcastState(r);broadcastLobbies()});
 s.on('watch-room',({code},ack)=>{code=String(code||'').trim().toUpperCase();const r=rooms.get(code);if(!r)return ack({error:'Raum nicht gefunden.'});r.spectators.add(s.id);s.join(code);s.data.room=code;s.data.role='spectator';ack({ok:true,code,role:'spectator',targetWins:r.targetWins});broadcastState(r)});
 s.on('choose',choice=>{const r=rooms.get(s.data.room),i=s.data.role;if(!r||!Number.isInteger(i)||!choices.has(choice)||r.phase!=='playing')return;const p=r.players[i];if(!p||p.ready)return;p.choice=choice;broadcastState(r)});
 s.on('ready',()=>{const r=rooms.get(s.data.room),i=s.data.role;if(!r||!Number.isInteger(i)||r.phase!=='playing')return;const p=r.players[i];if(!p||!p.choice||p.ready)return;p.ready=true;broadcastState(r);if(r.players.every(Boolean)&&r.players.every(p=>p.ready)){r.phase='countdown';io.to(r.code).emit('countdown',{seconds:3});let n=3;const t=setInterval(()=>{n--;if(n>0)io.to(r.code).emit('countdown',{seconds:n});else{clearInterval(t);finishRound(r)}},1000)}});
 s.on('leave-room',()=>{const r=rooms.get(s.data.room);if(!r)return;const i=s.data.role;r.spectators.delete(s.id);if(Number.isInteger(i)&&r.players[i]?.id===s.id){if(r.players[0]&&r.players[1]&&r.phase!=='finished')forfeit(r,i);else{r.players[i]=null;r.phase='waiting';broadcastState(r,'Ein Spieler hat den Raum verlassen.')}}s.leave(r.code);s.data.room=null;s.data.role=null;if(rooms.has(r.code))broadcastLobbies()});
 s.on('disconnect',()=>{const r=rooms.get(s.data.room);if(!r)return;r.spectators.delete(s.id);const i=s.data.role;if(Number.isInteger(i)&&r.players[i]?.id===s.id){if(r.players[0]&&r.players[1]&&r.phase!=='finished')forfeit(r,i);else{r.players[i]=null;r.phase='waiting';broadcastState(r,'Ein Spieler hat den Raum verlassen.')}}if(rooms.has(r.code)&&!r.players.some(Boolean)&&!r.spectators.size)rooms.delete(r.code);broadcastLobbies()})
});server.listen(PORT,()=>console.log(`RPS Arena läuft auf Port ${PORT}`));
